### ISSUE TITLE
Create, Read, Update

### ISSUE THREAD

**Issue by MunKeat** [CS2103JAN2016-W15-2J/main#1]
User must be able to _Create, Read, Update_ tasks in the To-Do List

**Comment by girish92** [comment]
Create, Read and Update is done on the logic's side. Waiting to integrate with Parser's code.

**Comment by MunKeat** [comment]
Create, Read, and Update successfully done for Floating Tasks. Refer to: [Makes basic edit work ](https://github.com/CS2103JAN2016-W15-2J/main/commit/6a4220bfdad62995650d2e1e95ad5f41f11e642d)
