### ISSUE TITLE
attempt to create a function to allow user to change path for the file storage

### ISSUE THREAD

**Issue by tharain** [CS2103JAN2016-W15-2J/main#20]

**Comment by MunKeat** [comment]
Related - Refer to: [Implement "Change File Path Command" feature #25](https://github.com/CS2103JAN2016-W15-2J/main/issues/25)

**Comment by tharain** [comment]
able to handle "C:/dir1/dir2/.../" OR "C:/dir1/dir2/.../newFileName.txt"
